export const SET_USER_DETAIL_SUCCESS = 'SET_USER_DETAIL_SUCCESS';
export const SET_USER_DETAIL_FAIL = 'SET_USER_DETAIL_FAIL';

export const SIGNUP_SUCCESS = 'SIGNUP_SUCCESS';
export const SIGNUP_FAIL = 'SIGNUP_FAIL';
export const LOGIN_SUCCESS = 'LOGIN_SUCCESS';
export const LOGIN_FAIL = 'LOGIN_FAIL';
export const ACTIVATION_SUCCESS = 'ACTIVATION_SUCCESS';
export const ACTIVATION_FAIL = 'ACTIVATION_FAIL';
export const RESET_PASSWORD_SUCCESS = 'RESET_PASSWORD_SUCCESS';
export const RESET_PASSWORD_FAIL = 'RESET_PASSWORD_FAIL';
export const RESET_PASSWORD_CONFIRM_SUCCESS = 'RESET_PASSWORD_CONFIRM_SUCCESS';
export const RESET_PASSWORD_CONFIRM_FAIL = 'RESET_PASSWORD_CONFIRM_FAIL';

export const SET_EMAIL_SUCCESS = 'SET_EMAIL_SUCCESS';
export const SET_EMAIL_FAIL = 'SET_EMAIL_FAIL';

export const SET_PASSWORD_SUCCESS = 'SET_PASSWORD_SUCCESS';
export const SET_PASSWORD_FAIL = 'SET_PASSWORD_FAIL';

export const LOGOUT = 'LOGOUT';
export const AUTHENTICATED_FAIL = 'AUTHENTICATED_FAIL';
export const AUTHENTICATED_SUCCESS = 'AUTHENTICATED_SUCCESS';
export const USER_LOADED_SUCCESS = 'USER_LOADED_SUCCESS';
export const USER_LOADED_FAIL = 'USER_LOADED_FAIL';
export const RESET_STATE = 'RESET_STATE';
////
export const LOAD_POSTS_SUCCESS = 'LOAD_POSTS_SUCCESS';
export const LOAD_POSTS_FAIL = 'LOAD_POSTS_FAIL';
export const LOAD_USER_POSTS_SUCCESS = 'LOAD_USER_POSTS_SUCCESS';
export const LOAD_USER_POSTS_FAIL = 'LOAD_USER_POSTS_FAIL';
export const LOAD_POST_SUCCESS = 'LOAD_POST_SUCCESS';
export const LOAD_POST_FAIL = 'LOAD_POST_FAIL';
export const FAVE_SUCCESS = 'FAVE_SUCCESS';
export const FAVE_FAIL = 'FAVE_FAIL';
export const LOAD_FAVE_SUCCESS = 'LOAD_FAVE_SUCCESS';
export const LOAD_FAVE_FAIL = 'LOAD_FAVE_FAIL';
export const LOAD_PROFILE_SUCCESS = 'LOAD_PROFILE_SUCCESS';
export const LOAD_PROFILE_FAIL = 'LOAD_PROFILE_FAIL';

export const LOAD_USERS_SUCCESS = 'LOAD_USERS_SUCCESS';
export const LOAD_USERS_FAIL = 'LOAD_USERS_FAIL';

export const NEW_POST_SUCCESS = 'NEW_POST_SUCCESS';
export const NEW_POST_FAIL = 'NEW_POST_FAIL';

export const FOLLOW_SUCCESS = 'FOLLOW_SUCCESS';
export const FOLLOW_FAIL = 'FOLLOW_FAIL';

export const UPDATE_AVATAR_SUCCESS = 'UPDATE_AVATAR_SUCCESS';
export const UPDATE_AVATAR_FAIL = 'UPDATE_AVATAR_FAIL';

export const LOAD_NOTIF_SUCCESS = 'LOAD_NOTIF_SUCCESS';
export const LOAD_NOTIF_FAIL = 'LOAD_NOTIF_FAIL';

export const LOAD_FOLLOWER_SUCCESS = 'LOAD_FOLLOWER_SUCCESS';
export const LOAD_FOLLOWER_FAIL = 'LOAD_FOLLOWER_FAIL';

export const LOAD_FOLLOWING_SUCCESS = 'LOAD_FOLLOWING_SUCCESS';
export const LOAD_FOLLOWING_FAIL = 'LOAD_FOLLOWING_FAIL';

export const LOAD_USER_FAVS_SUCCESS = 'LOAD_USER_FAVS_SUCCESS';
export const LOAD_USER_FAVS_FAIL = 'LOAD_USER_FAVS_FAIL';

export const LOAD_NOW_PLAYING_SUCCESS = 'LOAD_NOW_PLAYING_SUCCESS';
export const LOAD_NOW_PLAYING_FAIL = 'LOAD_NOW_PLAYING_FAIL';

export const SET_NOW_PLAYING_SUCCESS = 'SET_NOW_PLAYING_SUCCESS';

export const LOAD_CARD_POST_SUCCESS = 'LOAD_CARD_POST_SUCCESS';

export const LOAD_USER_PLAYLISTS_SUCCESS = 'LOAD_USER_PLAYLISTS_SUCCESS';
export const LOAD_USER_PLAYLISTS_FAIL = 'LOAD_USER_PLAYLISTS_FAIL';

export const LOAD_PLAYLIST_SUCCESS = 'LOAD_PLAYLIST_SUCCESS';
export const LOAD_PLAYLIST_FAIL = 'LOAD_PLAYLIST_FAIL';
